// Book files and covers live either in an S3-compatible bucket (Cloudflare R2
// in production) or, when no bucket is configured, in ./storage on disk.
import { randomUUID } from "node:crypto";
import { access, mkdir, open, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { AwsClient } from "aws4fetch";
import { makeToken } from "./token";

export const MAX_BOOK_BYTES = 300 * 1024 * 1024;
export const MAX_COVER_BYTES = 8 * 1024 * 1024;

export type ObjectKind = "pdf" | "epub" | "cover";

const UUID = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
const KEY_RE = new RegExp(`^(?:books/${UUID}\\.(?:pdf|epub)|covers/${UUID}\\.(?:jpg|png|webp))$`);

/** Keys are always generated by us; anything else is rejected everywhere. */
export function isValidKey(key: unknown): key is string {
  return typeof key === "string" && KEY_RE.test(key);
}

export function newKey(kind: ObjectKind, coverExt: "jpg" | "png" | "webp" = "jpg"): string {
  return kind === "cover" ? `covers/${randomUUID()}.${coverExt}` : `books/${randomUUID()}.${kind}`;
}

const CONTENT_TYPES: Record<string, string> = {
  pdf: "application/pdf",
  epub: "application/epub+zip",
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

export function contentTypeFor(key: string): string {
  return CONTENT_TYPES[key.slice(key.lastIndexOf(".") + 1)] ?? "application/octet-stream";
}

interface S3 {
  endpoint: string;
  bucket: string;
  publicUrl: string;
  client: AwsClient;
}

let s3Config: S3 | null | undefined;

function s3(): S3 | null {
  if (s3Config !== undefined) return s3Config;
  const { S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_PUBLIC_URL } = process.env;
  if (!S3_ENDPOINT || !S3_BUCKET || !S3_ACCESS_KEY_ID || !S3_SECRET_ACCESS_KEY || !S3_PUBLIC_URL) {
    s3Config = null;
    return null;
  }
  const region = process.env.S3_REGION || "auto";
  s3Config = {
    endpoint: S3_ENDPOINT.replace(/\/+$/, ""),
    bucket: S3_BUCKET,
    publicUrl: S3_PUBLIC_URL.replace(/\/+$/, ""),
    client: new AwsClient({
      accessKeyId: S3_ACCESS_KEY_ID,
      secretAccessKey: S3_SECRET_ACCESS_KEY,
      service: "s3",
      region,
    }),
  };
  return s3Config;
}

export function storageMode(): "s3" | "local" {
  return s3() ? "s3" : "local";
}

function objectUrl(cfg: S3, key: string): string {
  return `${cfg.endpoint}/${cfg.bucket}/${key}`;
}

/** URL the browser uses to read a file (reader, cover images). */
export function publicUrl(key: string): string {
  const cfg = s3();
  return cfg ? `${cfg.publicUrl}/${key}` : `/files/${key}`;
}

/** URL that makes the browser save the file under a readable name. */
export function downloadUrl(key: string, fileName: string): string {
  const cfg = s3();
  // Bucket objects carry their Content-Disposition from upload time.
  if (cfg) return `${cfg.publicUrl}/${key}`;
  return `/files/${key}?dl=${encodeURIComponent(fileName)}`;
}

function storageRoot(): string {
  // Local-only path: keep the bundler from tracing the whole project for it.
  return path.resolve(/*turbopackIgnore: true*/ process.env.STORAGE_DIR || path.join(process.cwd(), "storage"));
}

export function localPath(key: string): string {
  if (!isValidKey(key)) throw new Error("Invalid storage key");
  const root = storageRoot();
  const full = path.resolve(root, key);
  if (!full.startsWith(root + path.sep)) throw new Error("Invalid storage key");
  return full;
}

function assertLocalAllowed(): void {
  if (process.env.VERCEL) {
    throw new Error("Configure S3_* (Cloudflare R2) storage: Vercel has no persistent disk.");
  }
}

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

export async function putObject(
  key: string,
  body: Uint8Array,
  opts: { contentType: string; disposition?: string },
): Promise<void> {
  const cfg = s3();
  if (cfg) {
    const payload = new Uint8Array(body);
    const headers: Record<string, string> = {
      "Content-Type": opts.contentType,
      "Content-Length": String(payload.byteLength),
    };
    if (opts.disposition) headers["Content-Disposition"] = opts.disposition;
    const res = await cfg.client.fetch(objectUrl(cfg, key), {
      method: "PUT",
      body: payload,
      headers,
    });
    if (!res.ok) throw new Error(`Storage upload failed (${res.status})`);
    return;
  }
  assertLocalAllowed();
  const file = localPath(key);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, body, { flag: "wx" });
}

export interface UploadTarget {
  key: string;
  url: string;
  headers: Record<string, string>;
}

/**
 * Where the admin's browser should PUT a file: a presigned bucket URL, or our
 * own local upload route guarded by the admin cookie plus a key-bound token.
 */
export async function createUploadTarget(
  key: string,
  contentType: string,
  disposition?: string,
): Promise<UploadTarget> {
  const headers: Record<string, string> = { "Content-Type": contentType };
  const cfg = s3();
  if (cfg) {
    const url = new URL(objectUrl(cfg, key));
    url.searchParams.set("X-Amz-Expires", "3600");
    const signedHeaders: Record<string, string> = {};
    if (disposition) {
      signedHeaders["Content-Disposition"] = disposition;
      headers["Content-Disposition"] = disposition;
    }
    const signed = await cfg.client.sign(new Request(url, { method: "PUT", headers: signedHeaders }), {
      aws: { signQuery: true },
    });
    return { key, url: signed.url, headers };
  }
  assertLocalAllowed();
  const token = makeToken(process.env.SESSION_SECRET ?? "", `upload:${key}`, 3600);
  return {
    key,
    url: `/api/admin/upload?key=${encodeURIComponent(key)}&token=${encodeURIComponent(token)}`,
    headers,
  };
}

export class UploadTooLargeError extends Error {}

/** Streams a local upload to disk, refusing to overwrite or exceed maxBytes. */
export async function writeLocalUpload(
  key: string,
  body: ReadableStream<Uint8Array>,
  maxBytes: number,
): Promise<number> {
  assertLocalAllowed();
  const file = localPath(key);
  if (await exists(file)) throw new Error("File already exists");
  await mkdir(path.dirname(file), { recursive: true });
  const partial = `${file}.${randomUUID()}.part`;
  const handle = await open(partial, "wx");
  let written = 0;
  try {
    const reader = body.getReader();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      written += value.byteLength;
      if (written > maxBytes) {
        await reader.cancel();
        throw new UploadTooLargeError();
      }
      await handle.write(value);
    }
    await handle.close();
  } catch (err) {
    await handle.close().catch(() => undefined);
    await rm(partial, { force: true });
    throw err;
  }
  if (await exists(file)) {
    await rm(partial, { force: true });
    throw new Error("File already exists");
  }
  await rename(partial, file);
  return written;
}

/** First bytes of a stored object, for content sniffing. */
export async function readHead(key: string, bytes = 1024): Promise<Uint8Array | null> {
  const cfg = s3();
  if (cfg) {
    const res = await cfg.client.fetch(objectUrl(cfg, key), { headers: { Range: `bytes=0-${bytes - 1}` } });
    if (!res.ok) return null;
    return new Uint8Array(await res.arrayBuffer()).slice(0, bytes);
  }
  try {
    const handle = await open(/*turbopackIgnore: true*/ localPath(key), "r");
    try {
      const buffer = Buffer.alloc(bytes);
      const { bytesRead } = await handle.read(buffer, 0, bytes, 0);
      return new Uint8Array(buffer.subarray(0, bytesRead));
    } finally {
      await handle.close();
    }
  } catch {
    return null;
  }
}

/** The whole object as a stream (used to scan uploads), or null if missing. */
export async function openObject(key: string): Promise<ReadableStream<Uint8Array> | null> {
  const cfg = s3();
  if (cfg) {
    const res = await cfg.client.fetch(objectUrl(cfg, key));
    return res.ok && res.body ? res.body : null;
  }
  try {
    const { createReadStream } = await import("node:fs");
    const { Readable } = await import("node:stream");
    const file = localPath(key);
    await stat(/*turbopackIgnore: true*/ file);
    return Readable.toWeb(createReadStream(/*turbopackIgnore: true*/ file)) as ReadableStream<Uint8Array>;
  } catch {
    return null;
  }
}

export async function objectSize(key: string): Promise<number | null> {
  const cfg = s3();
  if (cfg) {
    const res = await cfg.client.fetch(objectUrl(cfg, key), { method: "HEAD" });
    if (!res.ok) return null;
    const size = Number(res.headers.get("content-length"));
    return Number.isFinite(size) ? size : null;
  }
  try {
    return (await stat(/*turbopackIgnore: true*/ localPath(key))).size;
  } catch {
    return null;
  }
}

export async function deleteObject(key: string | null | undefined): Promise<void> {
  if (!isValidKey(key)) return;
  try {
    const cfg = s3();
    if (cfg) await cfg.client.fetch(objectUrl(cfg, key), { method: "DELETE" });
    else await rm(localPath(key), { force: true });
  } catch (err) {
    console.error("[storage] delete failed:", key, err);
  }
}
