// Hand-picked Gutenberg classics (mostly fantasy, science fiction, fairy tales
// and adventure). Each one still goes through the copyright filter on import.
export const GUTENBERG_PICKS: { id: number; title: string }[] = [
  { id: 55, title: "The Wonderful Wizard of Oz" },
  { id: 54, title: "The Marvelous Land of Oz" },
  { id: 16, title: "Peter Pan" },
  { id: 12, title: "Through the Looking-Glass" },
  { id: 35, title: "The Time Machine" },
  { id: 36, title: "The War of the Worlds" },
  { id: 5230, title: "The Invisible Man" },
  { id: 159, title: "The Island of Doctor Moreau" },
  { id: 1013, title: "The First Men in the Moon" },
  { id: 236, title: "The Jungle Book" },
  { id: 2781, title: "Just So Stories" },
  { id: 829, title: "Gulliver's Travels" },
  { id: 2591, title: "Grimms' Fairy Tales" },
  { id: 1597, title: "Andersen's Fairy Tales" },
  { id: 503, title: "The Blue Fairy Book" },
  { id: 540, title: "The Red Fairy Book" },
  { id: 128, title: "The Arabian Nights Entertainments" },
  { id: 62, title: "A Princess of Mars" },
  { id: 78, title: "Tarzan of the Apes" },
  { id: 123, title: "At the Earth's Core" },
  { id: 551, title: "The Land That Time Forgot" },
  { id: 289, title: "The Wind in the Willows" },
  { id: 902, title: "The Happy Prince and Other Tales" },
  { id: 174, title: "The Picture of Dorian Gray" },
  { id: 10007, title: "Carmilla" },
  { id: 1952, title: "The Yellow Wallpaper" },
  { id: 325, title: "Phantastes" },
  { id: 708, title: "The Princess and the Goblin" },
  { id: 778, title: "Five Children and It" },
  { id: 836, title: "The Phoenix and the Carpet" },
  { id: 201, title: "Flatland" },
  { id: 3155, title: "She" },
  { id: 2166, title: "King Solomon's Mines" },
  { id: 120, title: "Treasure Island" },
  { id: 1268, title: "The Mysterious Island" },
  { id: 83, title: "From the Earth to the Moon" },
  { id: 103, title: "Around the World in Eighty Days" },
  { id: 164, title: "Twenty Thousand Leagues under the Sea" },
  { id: 18857, title: "A Journey to the Centre of the Earth" },
  { id: 500, title: "The Adventures of Pinocchio" },
  { id: 175, title: "The Phantom of the Opera" },
  { id: 68283, title: "The Call of Cthulhu" },
  { id: 18247, title: "The Last Man" },
  { id: 74, title: "The Adventures of Tom Sawyer" },
  { id: 76, title: "Adventures of Huckleberry Finn" },
  { id: 1184, title: "The Count of Monte Cristo" },
  { id: 1400, title: "Great Expectations" },
  { id: 98, title: "A Tale of Two Cities" },
];
