// Complete Arabic books from the Hindawi Foundation, checked to be republishable:
// each copyright page puts the whole edition under CC BY 4.0 and the original
// appeared before 1931 (the importer checks both again before saving). Ordered
// by priority: fantasy & sci-fi, children, novels, mystery, then true stories
// (biography, travel), short stories, plays and narrative history.
// Generated from a scan of safahat.org; titles are Hindawi's own.
import type { HindawiEntry } from "./hindawi";

export type HindawiPick = HindawiEntry & { title: string };

export const HINDAWI_PICKS: HindawiPick[] = [
  { id: "85849530", title: "طعام الآلهة وكيف جاء إلى الأرض", category: "fantasy", film: "The Food of the Gods (1976)", description: "عالمان يخترعان مادة تجعل كل ما يأكلها عملاقاً، فتبدأ الدجاجات والفئران والأطفال بالنمو بلا توقف." },
  { id: "27403814", title: "صانع المعجزات", category: "fantasy", film: "The Man Who Could Work Miracles (1936)", description: "موظف بسيط يكتشف فجأة أنه قادر على صنع المعجزات بكلمة واحدة، وتبدأ المشاكل." },
  { id: "91486168", title: "آلة الزمن", category: "fantasy", film: "The Time Machine (1960، 2002)", description: "رواية ويلز الشهيرة عن مخترع يسافر بآلته إلى عام 802701، فيجد البشرية قد انقسمت إلى شعبين غريبين. أصل كل قصص السفر عبر الزمن." },
  { id: "82686040", title: "حرب العوالم", category: "fantasy", film: "War of the Worlds (1953، 2005)", description: "مخلوقات من المريخ تهبط على إنكلترا بآلات ثلاثية الأرجل لا يقف أمامها شيء. الرواية التي صنعت خيال غزو الفضاء." },
  { id: "94073036", title: "جزيرة الدكتور مورو", category: "fantasy", film: "The Island of Dr. Moreau (1977، 1996)", description: "بحّار ناجٍ يصل إلى جزيرة نائية يحوّل فيها عالم مجنون الحيوانات إلى كائنات تشبه البشر." },
  { id: "47249605", title: "الأرض المسطحة: قصة خيالية متعددة الأبعاد", category: "fantasy", film: "Flatland: The Movie (2007)", description: "حكاية خيالية رياضية عن عالم مسطّح ذي بعدين، يكتشف فيه مربّعٌ وجود بُعد ثالث." },
  { id: "83594972", title: "إمبراطورية النمل", category: "fantasy", film: "Empire of the Ants (1977)" },
  { id: "53742042", title: "الطاعون القرمزي", category: "fantasy", description: "بعد عقود من وباء أباد البشرية، يحكي جدّ عجوز لأحفاده المتوحشين كيف انهار العالم المتحضّر في أيام." },
  { id: "94069172", title: "رجل الساعة الآلي", category: "fantasy" },
  { id: "74859409", title: "الزيارة المدهشة", category: "fantasy" },
  { id: "25093936", title: "حربنا مع إمارة موناكو", category: "fantasy" },
  { id: "18352740", title: "الرحلة الرهيبة للقارب «تود»", category: "fantasy" },
  { id: "58139737", title: "تاكي بومب: برهان رياضي", category: "fantasy" },
  { id: "13736816", title: "قصة الأيام القادمة", category: "fantasy" },
  { id: "17170975", title: "سيد المولدات الكهربائية", category: "fantasy" },
  { id: "37259528", title: "قصة الطوفان", category: "fantasy" },
  { id: "19750531", title: "فيلمَر", category: "fantasy" },
  { id: "16470718", title: "كهف الاسبلرجلز", category: "fantasy" },
  { id: "46970637", title: "القِمْع", category: "fantasy" },
  { id: "27494684", title: "كورو الرائع", category: "fantasy" },
  { id: "86059471", title: "دوارة الرياح الطائرة", category: "fantasy" },
  { id: "72586268", title: "حقائق قضية راتكليف", category: "fantasy" },
  { id: "83625319", title: "الرحلة الأخيرة للسفينة «يهوذا الإسخريوطي»", category: "fantasy" },
  { id: "59393029", title: "نوع نادر من الأشباح", category: "fantasy" },
  { id: "85175195", title: "تحت مِبضَع الجراح", category: "fantasy" },
  { id: "48592739", title: "العودة من العالم الآخر: قصة غريبة: تطبيق عملي لتجسد الأرواح", category: "fantasy" },
  { id: "80583686", title: "القَلَنسوَة الأُرجوانية", category: "fantasy" },
  { id: "35028686", title: "جنازة الشيطان", category: "fantasy" },
  { id: "74138503", title: "الفأر الشيطاني", category: "fantasy" },
  { id: "84027914", title: "تبادل الأرواح: الأمير ميكالسكوفيتش وعلاج الطبيب هاروود العجيب", category: "fantasy" },
  { id: "15070794", title: "يوم بين الكذابين", category: "fantasy" },
  { id: "48293606", title: "مطياف الروح: المادية الفريدة لمفكر تقدمي", category: "fantasy" },
  { id: "57904081", title: "الرجل الشفاف", category: "fantasy" },
  { id: "42051490", title: "رجل بلا جسد", category: "fantasy" },
  { id: "94750952", title: "الساعة التي دارت إلى الوراء", category: "fantasy" },
  { id: "79408082", title: "ابنة السيناتور", category: "fantasy" },
  { id: "61947057", title: "تجربة البروفيسور", category: "fantasy" },
  { id: "59391869", title: "سكويدز العجوز وسبيلر الصغير", category: "fantasy" },
  { id: "91924052", title: "الشجرة المنطاد", category: "fantasy" },
  { id: "49029496", title: "السفينة الأسطورية: قصة من الأيام الأولى لمستعمرة «نيو هافِن»", category: "fantasy" },
  { id: "85263961", title: "توءما آل فانشر", category: "fantasy" },
  { id: "97240268", title: "حالة التوءمين داو", category: "fantasy" },
  { id: "35152952", title: "مستعذبو الألم", category: "fantasy" },
  { id: "74186493", title: "أبرع رجل في العالم", category: "fantasy" },
  { id: "59390719", title: "زواج عجيب", category: "fantasy" },
  { id: "20815025", title: "تجربة الدكتور أوكس", category: "fantasy" },
  { id: "63817174", title: "تحوُّل", category: "fantasy" },
  { id: "97413503", title: "باطن الأرض: فجوة عملاقة تمتد عبر الكوكب من قطبه الشمالي إلى الجنوبي", category: "fantasy" },
  { id: "83825904", title: "الخطر!: من سجلات الكابتن جون سيرياس", category: "fantasy" },
  { id: "19302826", title: "تجربة جامعة كاينبلاتس الكبرى", category: "fantasy" },
  { id: "16850481", title: "شتاء وسط الجليد", category: "fantasy" },
  { id: "13153615", title: "لاسلكيًّا", category: "fantasy" },
  { id: "42905709", title: "آلة التفكيك", category: "fantasy" },
  { id: "14705258", title: "السيد زخاريوس", category: "fantasy" },
  { id: "46836370", title: "الحُلة الجميلة", category: "fantasy" },
  { id: "61950303", title: "عندما صرخت الأرض", category: "fantasy" },
  { id: "90590479", title: "في العام ٢٨٨٩", category: "fantasy" },
  { id: "90975190", title: "رحلة على متن منطاد", category: "fantasy" },
  { id: "15252631", title: "بلد العميان", category: "fantasy" },
  { id: "90695163", title: "قصة من العصر الحجري", category: "fantasy" },
  { id: "75379628", title: "غزاة البحر", category: "fantasy" },
  { id: "13964931", title: "صانع الألماس", category: "fantasy" },
  { id: "90736148", title: "جزيرة الإيبيورنيس", category: "fantasy" },
  { id: "82472790", title: "زهرة الأوركيد الغريبة", category: "fantasy" },
  { id: "30272952", title: "التفاحة", category: "fantasy" },
  { id: "30728384", title: "الأطفال الخمسة وعفريت الرمال", category: "children", film: "Five Children and It (2004)", description: "خمسة أطفال يعثرون في حفرة رملية على عفريت عجوز يحقق لهم أمنية كل يوم، لكن كل أمنية تنقلب مغامرة غير متوقعة." },
  { id: "37027416", title: "حكايات هانس أندرسن الخيالية: المجموعة الأولى", category: "children", film: "The Little Mermaid (1989)، Frozen (2013)", description: "حكايات أندرسن الساحرة: حورية البحر الصغيرة، وملكة الثلج، والبطة القبيحة، وغيرها." },
  { id: "62705804", title: "ديفيد كوبرفيلد: أعدَّتها للأطفال أليس إف جاكسون", category: "children", film: "David Copperfield (1935، 2019)", description: "قصة ديكنز الخالدة عن يتيم يشق طريقه في الحياة، في نسخة مبسطة للفتيان." },
  { id: "31717369", title: "أطفال السكة الحديدية", category: "children", film: "The Railway Children (1970، 2000)", description: "ثلاثة أطفال ينتقلون مع أمهم إلى الريف بعد سجن أبيهم ظلماً، فتصير سكة القطار القريبة عالمهم كله." },
  { id: "72597415", title: "الرياح وأشجار الصفصاف", category: "children", film: "The Wind in the Willows (1996)", description: "مغامرات الخلد والجرذ والغرير والضفدع المغرور على ضفاف النهر، من أحب كتب الأطفال في العالم." },
  { id: "86920724", title: "رابونزل وقصص أخرى", category: "children", film: "Snow White (1937)، Cinderella (1950)، Tangled (2010)", description: "حكايات الأخوين جريم: بياض الثلج، وسندريلا، ورابونزل، وهانسل وغريتل، وغيرها من الحكايات الشعبية الألمانية." },
  { id: "41979506", title: "يوميات فوكس ميكي", category: "children" },
  { id: "63708405", title: "عشرون قصة من روائع شكسبير", category: "children" },
  { id: "18528352", title: "قِصَصٌ صِينِيَّةٌ لِلْأَطْفَالِ", category: "children" },
  { id: "93947286", title: "مُغَامَرَاتُ بوب وايت", category: "children" },
  { id: "95247424", title: "مُغَامَرَاتُ الْقُنْدُسِ بادي", category: "children" },
  { id: "39260479", title: "الْغُرَابُ بلاكي", category: "children" },
  { id: "71417581", title: "الْجَدَّةُ ثعلبة الْعَجُوزُ", category: "children" },
  { id: "30473582", title: "سكارليت بيمبرنِل", category: "novels", film: "The Scarlet Pimpernel (1934، 1982)", description: "بطل مجهول يهرّب النبلاء من مقصلة الثورة الفرنسية ويترك وراءه زهرة حمراء صغيرة توقيعاً." },
  { id: "58257393", title: "العميل السري: حكاية بسيطة", category: "novels", film: "The Secret Agent (1996)", description: "عميل سري في لندن يتورط في مؤامرة تفجير، في رواية جوزيف كونراد عن الجاسوسية والإرهاب." },
  { id: "93029537", title: "إيفانهو", category: "novels", film: "Ivanhoe (1952)", description: "فارس سكسوني عائد من الحروب الصليبية في إنكلترا القرون الوسطى، بين روبن هود والملك ريتشارد قلب الأسد." },
  { id: "96415063", title: "كوخ العم توم", category: "novels", film: "Uncle Tom’s Cabin (1927، 1987)", description: "الرواية التي هزّت أمريكا عن معاناة العبيد، في نسخة للفتيان." },
  { id: "53179097", title: "الفرسان الثلاثة", category: "novels", film: "The Three Musketeers (1993، 2011)", description: "الشاب دارتانيان ينضم إلى الفرسان الثلاثة: أتوس وبورتوس وأراميس، في مغامرات المبارزة والدسائس في فرنسا." },
  { id: "46094724", title: "الأجنحة المتكسرة", category: "novels", film: "الأجنحة المتكسرة (1962)", description: "رواية جبران عن حب شاب لسلمى كرامة وما يصطدم به من قيود المجتمع والتقاليد، بلغة شعرية مؤثرة." },
  { id: "28493759", title: "زينب", category: "novels", film: "زينب (1930، 1952)", description: "من أوائل الروايات العربية الحديثة: قصة حب في ريف مصر بين زينب الفلاحة وشباب القرية." },
  { id: "52508494", title: "بيت السهم", category: "mystery", film: "The House of the Arrow (1940، 1953)" },
  { id: "25297192", title: "النفط", category: "novels", film: "There Will Be Blood (2007)" },
  { id: "85731606", title: "مُربي النحل", category: "novels", film: "The Keeper of the Bees (1935، 1947)" },
  { id: "90463596", title: "حي بن يقظان", category: "philosophy", description: "قصة فلسفية عن إنسان نشأ وحيداً في جزيرة معزولة، فتعلّم بالتأمل والعقل حتى وصل إلى معرفة الكون وخالقه." },
  { id: "20504275", title: "سجين حجر الأوبال", category: "mystery" },
  { id: "93859204", title: "قضية فندق سميراميس", category: "mystery" },
  { id: "38358209", title: "جريمة قتل في صف انتظار", category: "mystery" },
  { id: "92504085", title: "١٠٠٪: قصة مناضل وطني", category: "novels" },
  { id: "48080926", title: "الثابت", category: "novels" },
  { id: "82835153", title: "مملكة الفحم", category: "novels" },
  { id: "14697506", title: "ذو العباءة الخضراء", category: "novels" },
  { id: "64036461", title: "نفوس متقلبة", category: "novels" },
  { id: "48616852", title: "أوائل الخريف: قصة سيدة راقية", category: "novels" },
  { id: "84282618", title: "تحويلة مانهاتن", category: "novels" },
  { id: "46909507", title: "لا دام دي مونسورو", category: "novels" },
  { id: "91704704", title: "شهداء التعصب:  رواية تاريخية وقعت أكثر حوادثها في فرنسا على عهد فرنسوا الثاني ملك فرنسا المتوفى سنة ١٥٦٠م", category: "novels" },
  { id: "27380519", title: "ربيبة الدير: أم روكامبول (الجزء الأول)", category: "novels" },
  { id: "29392697", title: "المتوالي الصالح", category: "novels" },
  { id: "42486196", title: "التحفة العامية في قصة فنيانوس", category: "novels" },
  { id: "85794209", title: "في زمننا", category: "novels" },
  { id: "68483920", title: "أحزان فرتر", category: "novels" },
  { id: "82416046", title: "عذراء الهند", category: "novels" },
  { id: "59270690", title: "غصن البان في رياض الجنان", category: "novels" },
  { id: "24268395", title: "سر الاعتراف", category: "novels" },
  { id: "68690597", title: "العمال الصالحون", category: "novels" },
  { id: "83940694", title: "عذراء دنشواي", category: "novels" },
  { id: "53626279", title: "المكاري والكاهن", category: "novels" },
  { id: "38184164", title: "الوحش الضاري", category: "novels" },
  { id: "38381358", title: "الصديق المجهول", category: "novels" },
  { id: "59138396", title: "بديعة وفؤاد", category: "novels" },
  { id: "80603582", title: "أمير لبنان", category: "novels" },
  { id: "47351684", title: "قلب الرجل", category: "novels" },
  { id: "49195362", title: "آدم الجديد: رواية اجتماعية عصرية", category: "novels" },
  { id: "82495926", title: "أسرار مصر", category: "novels" },
  { id: "71361816", title: "الملك كورش", category: "novels" },
  { id: "36246180", title: "الدموع", category: "novels" },
  { id: "63836908", title: "قرة العين في خريدة لبنان", category: "novels" },
  { id: "70931790", title: "جوسلين", category: "novels" },
  { id: "19395315", title: "اليتيم", category: "novels" },
  { id: "58253951", title: "ضحايا العفاف", category: "novels" },
  { id: "60626970", title: "حواء الجديدة", category: "novels" },
  { id: "85252495", title: "فاتنة الإمبراطور: فرانسوا جوزيف إمبراطور النمسا السابق وعشيقته كاترين شراط", category: "novels" },
  { id: "63724059", title: "في وادي الهموم", category: "novels" },
  { id: "81713528", title: "وداعًا أيها الشرق", category: "novels" },
  { id: "83515363", title: "أسرار القصور: سياسية، تاريخية، غرامية، أدبية", category: "novels" },
  { id: "35718525", title: "الإيمان: رواية تاريخية مصرية", category: "novels" },
  { id: "93524790", title: "الحقيبة الزرقاء: رواية عصرية أدبية غرامية", category: "novels" },
  { id: "81936309", title: "الغادة الإنجليزية", category: "novels" },
  { id: "74280904", title: "ماجدولين", category: "novels" },
  { id: "24070363", title: "زنبقة الغور", category: "novels" },
  { id: "85247571", title: "في سبيل التاج", category: "novels" },
  { id: "39464158", title: "خارج الحريم", category: "novels" },
  { id: "16281941", title: "خاتمة روكامبول: روكامبول (الجزء السابع عشر)", category: "novels" },
  { id: "86905264", title: "مذكرة مجنون: روكامبول (الجزء السادس عشر)", category: "novels" },
  { id: "30938402", title: "روكامبول في السجن: روكامبول (الجزء الخامس عشر)", category: "novels" },
  { id: "71717370", title: "تلميذ روكامبول: روكامبول (الجزء الرابع عشر)", category: "novels" },
  { id: "69407460", title: "قلب المرأة: روكامبول (الجزء الثالث عشر)", category: "novels" },
  { id: "27150503", title: "ابن أرلندا: روكامبول (الجزء الثاني عشر)", category: "novels" },
  { id: "71904803", title: "كنوز الهند: روكامبول (الجزء الحادي عشر)", category: "novels" },
  { id: "69151868", title: "البستانية الحسناء: روكامبول (الجزء العاشر)", category: "novels" },
  { id: "73904174", title: "ملايين النورية: روكامبول (الجزء التاسع)", category: "novels" },
  { id: "57370939", title: "ضحايا الهند: روكامبول (الجزء الثامن)", category: "novels" },
  { id: "80940860", title: "العاشقة الروسية: روكامبول (الجزء السابع)", category: "novels" },
  { id: "72979479", title: "روكامبول في سيبريا: روكامبول (الجزء السادس)", category: "novels" },
  { id: "84919616", title: "سجن طولون: روكامبول (الجزء الخامس)", category: "novels" },
  { id: "57158406", title: "انتقام باكارا: روكامبول (الجزء الرابع)", category: "novels" },
  { id: "62753940", title: "الغادة الإسبانية: روكامبول (الجزء الثالث)", category: "novels" },
  { id: "46362904", title: "التوبة الكاذبة: روكامبول (الجزء الثاني)", category: "novels" },
  { id: "25791397", title: "الإرث الخفي: روكامبول (الجزء الأول)", category: "novels" },
  { id: "83972649", title: "سقوط غرناطة", category: "novels" },
  { id: "83858057", title: "غابة الحق", category: "novels" },
  { id: "20579040", title: "قلب الأسد", category: "novels" },
  { id: "27916469", title: "الشاعر", category: "novels" },
  { id: "92903907", title: "الباريسية الحسناء", category: "novels" },
  { id: "73918028", title: "أورشليم الجديدة", category: "novels" },
  { id: "82418169", title: "المحالفة الثلاثية في المملكة الحيوانية", category: "novels" },
  { id: "80272839", title: "عبرة التاريخ", category: "novels" },
  { id: "36950604", title: "الوحش . الوحش . الوحش", category: "novels" },
  { id: "59429042", title: "فتاة غسَّان", category: "novels" },
  { id: "37972959", title: "بدائع الخيال", category: "novels" },
  { id: "30709294", title: "ملكة القلوب", category: "novels" },
  { id: "70246068", title: "الدِّينُ والعِلمُ والمال", category: "novels" },
  { id: "26938058", title: "الانقلاب العثماني", category: "novels" },
  { id: "14642863", title: "قصص مختلفة: مجموعة قصص مثالية حديثة لأمم مختلفة", category: "novels" },
  { id: "96869297", title: "سانين", category: "novels" },
  { id: "46425061", title: "ملك النَّوَر", category: "novels" },
  { id: "74268029", title: "عبد الرحمن الناصر", category: "novels" },
  { id: "81407240", title: "المملوك الشارد", category: "novels" },
  { id: "40915851", title: "فتح الأندلس", category: "novels" },
  { id: "81504027", title: "العباسة أخت الرشيد", category: "novels" },
  { id: "61641316", title: "شارل وعبد الرحمن", category: "novels" },
  { id: "75919582", title: "الأمين والمأمون", category: "novels" },
  { id: "31641375", title: "جهاد المحبين", category: "novels" },
  { id: "29513059", title: "أسير المتمهدي", category: "novels" },
  { id: "13595164", title: "الحجاج بن يوسف", category: "novels" },
  { id: "69729647", title: "فتاة القيروان", category: "novels" },
  { id: "39482082", title: "صـلاح الـدين الأيـوبي", category: "novels" },
  { id: "36379464", title: "عـروس فرغانة", category: "novels" },
  { id: "92527518", title: "عذراء قريش", category: "novels" },
  { id: "13604281", title: "غَادَةُ كرْبَلاء", category: "novels" },
  { id: "41728357", title: "أبو مسلم الخراساني", category: "novels" },
  { id: "96940275", title: "١٧ رمضان", category: "novels" },
  { id: "49242828", title: "لادياس", category: "novels" },
  { id: "92031406", title: "استبداد المماليك", category: "novels" },
  { id: "83513693", title: "شجرة الدر", category: "novels" },
  { id: "71858151", title: "أرمانوسة المصرية", category: "novels" },
  { id: "91708090", title: "أحمد بن طولون", category: "novels" },
  { id: "94926286", title: "رجال العدالة الأربعة", category: "mystery", film: "The Four Just Men (1939)", description: "أربعة رجال غامضون يحققون العدالة بأيديهم حين يعجز القانون." },
  { id: "37195261", title: "درجات السلم التسع والثلاثون", category: "mystery", film: "The 39 Steps (1935، 1959)", description: "رجل بريء يجد جثة في شقته فيهرب عبر اسكتلندا مطارَداً من الشرطة والجواسيس معاً، وفي يده سرٌّ قد يشعل حرباً." },
  { id: "52848020", title: "الصليب الأزرق: نقاء الأب براون (١)", category: "mystery", film: "Father Brown (1954)", description: "أول ظهور للأب براون، القسيس البسيط الذي يكشف الجرائم بفهمه للنفس البشرية." },
  { id: "73928048", title: "علامة الأربعة", category: "mystery", film: "The Sign of Four (1983)", description: "شيرلوك هولمز ود. واطسون يلاحقان سرّ كنز هندي مسروق ورجلاً بساق خشبية." },
  { id: "28495060", title: "جريمتا شارع مورج", category: "mystery", film: "Murders in the Rue Morgue (1932، 1971)", description: "جريمة مروّعة في غرفة مغلقة في باريس، ومحقق عبقري يحلّها. القصة التي ولدت منها القصص البوليسية." },
  { id: "20949628", title: "قضية ليفنوورث", category: "mystery", film: "The Leavenworth Case (1936)" },
  { id: "85208528", title: "الاحتيال الكبير", category: "mystery", film: "The Great Impersonation (1935، 1942)" },
  { id: "26950502", title: "دليل الشمعة الملتوية", category: "mystery", film: "The Clue of the Twisted Candle (1960)" },
  { id: "64158279", title: "لغز أزهار النرجس", category: "mystery", film: "The Devil’s Daffodil (1961)" },
  { id: "83182427", title: "مغامرة تماثيل نابليون الستة", category: "mystery", film: "The Pearl of Death (1944)" },
  { id: "13949592", title: "فضيحة في بوهيميا", category: "mystery", description: "ملك بوهيميا يطلب مساعدة شيرلوك هولمز لاستعادة صورة قد تفضحه، فيلتقي هولمز بالمرأة الوحيدة التي هزمته." },
  { id: "51737031", title: "بصمة الإبهام الحمراء", category: "mystery" },
  { id: "29039297", title: "حتى آخر فلس: انتقام عالِم", category: "mystery" },
  { id: "41392619", title: "الرهائن الثلاث", category: "mystery" },
  { id: "25153916", title: "لغز المنزل ٣١ نيو إن", category: "mystery" },
  { id: "80383928", title: "طبيب الجريمة", category: "mystery" },
  { id: "61828647", title: "رجال العدالة الثلاثة", category: "mystery" },
  { id: "24290624", title: "جريمتا واجهة العرض", category: "mystery" },
  { id: "40579693", title: "أمين خزانة البلدة", category: "mystery" },
  { id: "71393685", title: "لغز محطة تشارينج كروس", category: "mystery" },
  { id: "81747580", title: "أموال الموتى", category: "mystery" },
  { id: "35083053", title: "صخرة في بحر البلطيق", category: "mystery" },
  { id: "27425937", title: "زمردات ليدي أليشيا", category: "mystery" },
  { id: "49418585", title: "مملكة العميان", category: "mystery" },
  { id: "63903074", title: "مخلب الشيطان", category: "mystery" },
  { id: "64797262", title: "صانع السيوف", category: "mystery" },
  { id: "64686407", title: "جريمة ميدل تمبل", category: "mystery" },
  { id: "52951836", title: "مغامرة شيرلو كومبس", category: "mystery" },
  { id: "38364297", title: "لغز ماركنمور", category: "mystery" },
  { id: "83915352", title: "اللورد سترانلي الشاب", category: "mystery" },
  { id: "73069616", title: "الخدمة السرية أو ذكريات محقق في المدينة", category: "mystery" },
  { id: "79496915", title: "مغامرة الغنيمة الثانية", category: "mystery" },
  { id: "80271480", title: "لغز بارادايس", category: "mystery" },
  { id: "63052914", title: "من عالم الأرواح", category: "mystery" },
  { id: "14640613", title: "إطلاق سراح وايومينج إد", category: "mystery" },
  { id: "80920418", title: "الشبح ذو القدم المعوجة", category: "mystery" },
  { id: "97068250", title: "وسط أجراس الخطر", category: "mystery" },
  { id: "38290520", title: "الوجه والقناع", category: "mystery" },
  { id: "90705950", title: "انتقام!", category: "mystery" },
  { id: "74250917", title: "تَدخُّل امرأة", category: "mystery" },
  { id: "51593795", title: "عقل السيد جيه جي ريدر", category: "mystery" },
  { id: "46830495", title: "عودة رجال العدالة الثلاثة", category: "mystery" },
  { id: "69086974", title: "عين أوزيريس", category: "mystery" },
  { id: "79242407", title: "المُحققة", category: "mystery" },
  { id: "71693707", title: "قضايا جون ثورندايك", category: "mystery" },
  { id: "28058403", title: "قانون رجال العدالة الأربعة", category: "mystery" },
  { id: "37904097", title: "دفتر قضايا الدكتور ثورندايك", category: "mystery" },
  { id: "28474802", title: "رجال عدالة قرطبة", category: "mystery" },
  { id: "94264040", title: "لغز البورتريه الكبير وقصص أخرى", category: "mystery" },
  { id: "18142526", title: "الصحفية جيني باكستر", category: "mystery" },
  { id: "27171803", title: "القفل العجيب", category: "mystery" },
  { id: "46179681", title: "مجلس العدالة", category: "mystery" },
  { id: "83159415", title: "المُحقق الخاص: مجموعة تجليات من واقع قضايا الشرطة", category: "mystery" },
  { id: "48619149", title: "مغامرات الدكتور ثورندايك: العظمة المُغنِّية", category: "mystery" },
  { id: "60472797", title: "سر فلامبو: سر الأب براون (٤٢)", category: "mystery" },
  { id: "48186172", title: "مكلوم مارن: سر الأب براون (٤١)", category: "mystery" },
  { id: "41807926", title: "قمر ميرو الأحمر: سر الأب براون (٤٠)", category: "mystery" },
  { id: "31470309", title: "أبشع جريمة في الدنيا : سر الأب براون (٣٩)", category: "mystery" },
  { id: "58625908", title: "اختفاء فودري: سر الأب براون (٣٨)", category: "mystery" },
  { id: "26363024", title: "الممثلون وحجة الغياب: سر الأب براون (٣٧)", category: "mystery" },
  { id: "19151364", title: "أغنية الأسماك الطائرة : سر الأب براون (٣٦)", category: "mystery" },
  { id: "83161391", title: "ذو اللحيتَين: سر الأب براون (٣٥)", category: "mystery" },
  { id: "70613507", title: "مرآة القاضي: سر الأب براون (٣٤)", category: "mystery" },
  { id: "29570209", title: "سر الأب براون: سر الأب براون (٣٣)", category: "mystery" },
  { id: "95817026", title: "شبح جديون وايز: شكُّ الأب براون (٣٢)", category: "mystery" },
  { id: "61837485", title: "مصير آل دارناواي: شكُّ الأب براون (٣١)", category: "mystery" },
  { id: "27496828", title: "الخنجر المجنح: شكُّ الأب براون (٣٠)", category: "mystery" },
  { id: "95705029", title: "لعنة الصليب الذهبي: شكُّ الأب براون (٢٩)", category: "mystery" },
  { id: "86937931", title: "معجزة مون كريسينت: شكُّ الأب براون (٢٨)", category: "mystery" },
  { id: "81863920", title: "وحي الكلب: شكُّ الأب براون (٢٧)", category: "mystery" },
  { id: "64941742", title: "سهم السماء: شكُّ الأب براون (٢٦)", category: "mystery" },
  { id: "29363803", title: "قيامة الأب براون: شكُّ الأب براون (٢٥)", category: "mystery" },
  { id: "50918028", title: "قصة الأب براون الخيالية: حكمة الأب براون (٢٤)", category: "mystery" },
  { id: "31490462", title: "جريمة جون بولنوي الغريبة: حكمة الأب براون (٢٣)", category: "mystery" },
  { id: "50205084", title: "سَلَطَة الكولونيل كراي: حكمة الأب براون (٢٢)", category: "mystery" },
  { id: "20408692", title: "إله الصنوج: حكمة الأب براون (٢١)", category: "mystery" },
  { id: "80838157", title: "هلاك آل بندراجون: حكمة الأب براون (٢٠)", category: "mystery" },
  { id: "28535931", title: "الباروكة الأرجوانية: حكمة الأب براون (١٩)", category: "mystery" },
  { id: "90202793", title: "رأس قيصر: حكمة الأب براون (١٨)", category: "mystery" },
  { id: "36497285", title: "خطأ الآلة: حكمة الأب براون (١٧)", category: "mystery" },
  { id: "46270963", title: "رجل الممر: حكمة الأب براون (١٦)", category: "mystery" },
  { id: "30940696", title: "مبارزة الدكتور هيرش: حكمة الأب براون (١٥)", category: "mystery" },
  { id: "79282927", title: "جنة اللصوص: حكمة الأب براون (١٤)", category: "mystery" },
  { id: "75719319", title: "غياب السيد جلاس: حكمة الأب براون (١٣)", category: "mystery" },
  { id: "47260852", title: "أدوات الموت الثلاث: نقاء الأب براون (١٢)", category: "mystery" },
  { id: "36831961", title: "علامة السيف المكسور: نقاء الأب براون (١١)", category: "mystery" },
  { id: "61508693", title: "عين أبولو: نقاء الأب براون (١٠)", category: "mystery" },
  { id: "64186353", title: "مطرقة الإله: نقاء الأب براون (٩)", category: "mystery" },
  { id: "64719352", title: "خطايا الأمير سارادين: نقاء الأب براون (٨)", category: "mystery" },
  { id: "14737094", title: "الشكل الخطأ: نقاء الأب براون (٧)", category: "mystery" },
  { id: "64759258", title: "شرف إزرائيل جاو: نقاء الأب براون (٦)", category: "mystery" },
  { id: "28146131", title: "الرجل الخفي: نقاء الأب براون (٥)", category: "mystery" },
  { id: "18190630", title: "النجوم الطائرة: نقاء الأب براون (٤)", category: "mystery" },
  { id: "31572902", title: "أقدام غريبة: نقاء الأب براون (٣)", category: "mystery" },
  { id: "29194073", title: "الحديقة السرية: نقاء الأب براون (٢)", category: "mystery" },
  { id: "82094946", title: "معضلة الزنزانة رقم ١٣", category: "mystery" },
  { id: "82793686", title: "لغز الخيط القرمزي", category: "mystery" },
  { id: "62064075", title: "مغامرة شوسكوم أولد بليس", category: "mystery" },
  { id: "61520283", title: "مغامرة رَجل الطلاء المتقاعد", category: "mystery" },
  { id: "71757280", title: "قضية جسر ثُور", category: "mystery" },
  { id: "93692485", title: "قضية هوية", category: "mystery" },
  { id: "96474251", title: "ذو الشفة الملتوية", category: "mystery" },
  { id: "69404051", title: "مغامرة مدرسة الرهبان", category: "mystery" },
  { id: "42475809", title: "لغز العِقد المفقود", category: "mystery" },
  { id: "82484081", title: "مغامرة البقعة الثانية", category: "mystery" },
  { id: "61517163", title: "عصابة شاردي الذهن", category: "mystery" },
  { id: "58690480", title: "لغز الشفرة القاتلة", category: "mystery" },
  { id: "14042824", title: "مغامرة مخططات بروس بارتينجتون", category: "mystery" },
  { id: "13035305", title: "مغامرة العميل المرموق", category: "mystery" },
  { id: "71964030", title: "مغامرة مصاصة دماء ساسكس", category: "mystery" },
  { id: "40927504", title: "مغامرة ثلاثة رجال يحملون اللقب جاريديب", category: "mystery" },
  { id: "96974046", title: "لغز الراديوم المفقود", category: "mystery" },
  { id: "83951748", title: "مغامرة لُبْدة الأَسَد", category: "mystery" },
  { id: "80282026", title: "مغامرة الرجل الزاحف", category: "mystery" },
  { id: "28153725", title: "لغز لوحة روبنز المسروقة", category: "mystery" },
  { id: "24146069", title: "مغامرة لاعب الرجبي المختفي", category: "mystery" },
  { id: "60630741", title: "اختفاء السيدة فرانسيس كارفاكس", category: "mystery" },
  { id: "37419061", title: "المغامرة الأخيرة: خاتمة أعمال شيرلوك هولمز", category: "mystery" },
  { id: "24928264", title: "مغامرة نظَّارة الأنف الذهبية", category: "mystery" },
  { id: "40942914", title: "مغامرة الدائرة الحمراء", category: "mystery" },
  { id: "48529592", title: "مغامرة الجندي الشاحب", category: "mystery" },
  { id: "28269058", title: "مغامرة الرجال الراقصين", category: "mystery" },
  { id: "64860839", title: "مغامرة جوهرة مازارين", category: "mystery" },
  { id: "69192647", title: "مغامرة تشارلز أوجستس ميلفيرتون", category: "mystery" },
  { id: "96151641", title: "مغامرة المنزل ذي الأسقفِ المُحدَّبة الثلاثة", category: "mystery" },
  { id: "85159629", title: "مغامرة بيتر الأسود", category: "mystery" },
  { id: "13181417", title: "مغامرة راكبة الدراجة في الطريق المهجور", category: "mystery" },
  { id: "17248486", title: "لغز رامي القنبلة", category: "mystery" },
  { id: "75179252", title: "مغامرة منزل آبي جرينج", category: "mystery" },
  { id: "13649293", title: "أنت من فعلها!", category: "mystery" },
  { id: "83809639", title: "مغامرة النزيلة الملثمة", category: "mystery" },
  { id: "97575964", title: "دليل الملاعق الفضية", category: "mystery" },
  { id: "74931718", title: "لغز الثروة المفقودة", category: "mystery" },
  { id: "17271642", title: "لغز الشبح المشتعل", category: "mystery" },
  { id: "25753861", title: "مغامرة قدم الشيطان", category: "mystery" },
  { id: "63130482", title: "مغامرة المحقق المحتضر", category: "mystery" },
  { id: "81830758", title: "مغامرة المنزل الخالي", category: "mystery" },
  { id: "25148242", title: "لغز الماسات الخمسمائة", category: "mystery" },
  { id: "61961973", title: "ألف ليلة وليلة (الجزء الأول)", category: "fantasy", film: "Aladdin (1992، 2019)، The 7th Voyage of Sinbad (1958)", originalYear: 1835, description: "الجزء الأول من الحكايات الشهيرة التي ترويها شهرزاد للملك شهريار ليلة بعد ليلة." },
  { id: "36973840", title: "ألف ليلة وليلة (الجزء الثاني)", category: "fantasy", originalYear: 1835 },
  { id: "85931905", title: "ألف ليلة وليلة (الجزء الثالث)", category: "fantasy", originalYear: 1835 },
  { id: "39419251", title: "ألف ليلة وليلة (الجزء الرابع)", category: "fantasy", originalYear: 1835 },
  { id: "75264279", title: "ألف ليلة وليلة (الجزء الخامس)", category: "fantasy", originalYear: 1835 },
  { id: "27482482", title: "ألف ليلة وليلة (الجزء السادس)", category: "fantasy", originalYear: 1835 },
  { id: "94061468", title: "النظرات", category: "literature", description: "مقالات وقصص المنفلوطي التي أبكت أجيالاً، بأسلوبه العذب في الأدب والمجتمع والحياة." },
  { id: "97086179", title: "طوق الحمامة", category: "literature", description: "رسالة ابن حزم في الحب وأحواله: علاماته وأسبابه وأنواعه، مع أخبار وأشعار وتجارب من عصره." },
  { id: "95904020", title: "رسالة الغفران", category: "literature", description: "رحلة خيالية يتصوّر فيها أبو العلاء المعري صديقه ابن القارح في الجنة والنار يحاور الشعراء واللغويين." },
  { id: "30953836", title: "عامل التحويلة", category: "novels" },
  { id: "85205353", title: "الإلياذة", category: "fantasy", film: "Troy (2004)", description: "ملحمة هوميروس عن حرب طروادة وغضب آخيل، في ترجمة سليمان البستاني الشعرية الشهيرة." },
  { id: "73806946", title: "مهاتما غاندي", category: "history", film: "Gandhi (1982)", description: "سيرة غاندي ونضاله السلمي من أجل استقلال الهند، كتبها رومان رولان." },
  { id: "51691461", title: "سيرة الفاتح", category: "history", film: "Fetih 1453 (2012)", description: "سيرة السلطان محمد الفاتح وفتح القسطنطينية." },
  { id: "30713151", title: "تشارلز داروين: حياته وخطاباته (الجزء الأول): مع فصل سيرة ذاتية بقلم تشارلز داروين", category: "history", film: "Creation (2009)" },
  { id: "19475069", title: "مذكرات الليدي هيستر ستانهوب: كما روتها بنفسها في محادثاتها مع طبيبها الخاص دكتور تشارلز لويس ميريون", category: "history" },
  { id: "28271586", title: "تشارلز داروين: حياته وخطاباته (الجزء الثاني)", category: "history" },
  { id: "69491491", title: "تاريخ هنيبال", category: "history" },
  { id: "30483160", title: "حول سرير الإمبراطور", category: "history" },
  { id: "18531604", title: "سعد في حياته الخاصة", category: "history" },
  { id: "93681649", title: "شهيرات النساء في العالم الإسلامي", category: "history" },
  { id: "69369183", title: "تاريخ نابوليون بونابرت: ١٧٦٩–١٨٢١", category: "history" },
  { id: "25936081", title: "ابن المقفع: أئمة الأدب (الجزء الثاني)", category: "history" },
  { id: "35168479", title: "الجاحظ: أئمة الأدب (الجزء الأول)", category: "history" },
  { id: "58481696", title: "صلاح الدين الأيوبي", category: "history" },
  { id: "30807493", title: "أدبيات اللغة العربية", category: "history" },
  { id: "15073074", title: "أمين الريحاني: ناشر فلسفة الشرق في بلاد الغرب", category: "history" },
  { id: "38039429", title: "الدر المنثور في طبقات ربات الخدور", category: "history" },
  { id: "25263526", title: "كلمة على رياض باشا: وصفحة من تاريخ مصر الحديث تتضمن خلاصة حياته", category: "history" },
  { id: "63836061", title: "حياة ابن خلدون ومُثل من فلسفته الاجتماعية", category: "history" },
  { id: "61404864", title: "مصارع الأعيان", category: "history" },
  { id: "31618696", title: "مذهب تولستوي", category: "history" },
  { id: "62929363", title: "البهاء زهير", category: "history" },
  { id: "90971751", title: "حياتي", category: "history" },
  { id: "83520394", title: "تراجم مصرية وغربية", category: "history" },
  { id: "19027171", title: "باحثة البادية", category: "history" },
  { id: "30427571", title: "عائشة تيمور", category: "history" },
  { id: "46979259", title: "وَرْدَةُ اليَازجِي", category: "history" },
  { id: "30615370", title: "رحلة ابن بطوطة: تحفة النظار في غرائب الأمصار وعجائب الأسفار", category: "history", film: "Journey to Mecca (2009)", description: "رحلة الرحّالة المغربي ابن بطوطة عبر العالم الإسلامي وآسيا وأفريقيا في القرن الثامن الهجري، وما رآه من بلدان وعادات وعجائب." },
  { id: "35058486", title: "رحلة إلى أوروبا ١٩١٢", category: "history", description: "رحلة جرجي زيدان إلى أوربا سنة 1912، ووصفه لمدنها وأهلها وحضارتها." },
  { id: "46205086", title: "تخليص الإبريز في تلخيص باريز", category: "history", description: "رحلة رفاعة الطهطاوي إلى باريس في عهد محمد علي، وما رآه هناك من علوم وعادات ونظام." },
  { id: "59728170", title: "البحر وسردينيا", category: "history" },
  { id: "82613636", title: "رحلة مِشعل المَحمل", category: "history" },
  { id: "42815371", title: "الرحلة الأولى للبحث عن ينابيع البحر الأبيض: النيل الأبيض", category: "history" },
  { id: "26183813", title: "الرحلة إلى أمريكا", category: "history" },
  { id: "97517380", title: "حكايات المهجر", category: "history" },
  { id: "83158373", title: "ملوك العرب", category: "history" },
  { id: "49706148", title: "مشاهدات سائح في الممالك الأوروبية", category: "history" },
  { id: "61386419", title: "مشاهد الممالك", category: "history" },
  { id: "48383159", title: "جزيرة رودس: جغرافيتها وتاريخها وآثارها، تليها خلاصة تاريخية عن أشهر جزائر بحر إيجه", category: "history" },
  { id: "60292585", title: "حضارة العرب في الأندلس: رسائل تاريخية في قالب خيالي بديع", category: "history" },
  { id: "57138360", title: "رحلة سمو الأمير الجليل محمد علي إلى جاوة", category: "history" },
  { id: "93814751", title: "رحلة الصيف إلى بلاد البوسنة والهرسك", category: "history" },
  { id: "90684824", title: "رحلة أول شرقي إلى أمركة", category: "history" },
  { id: "81869031", title: "الرحلة اليابانية", category: "history" },
  { id: "40206035", title: "سياحة في الروسيا", category: "history" },
  { id: "50640694", title: "الرحلة الشامية", category: "history" },
  { id: "83970509", title: "بيروت ولبنان منذ قرن ونصف القرن", category: "history" },
  { id: "84130273", title: "الواسطة في معرفة أحوال مالطة", category: "history" },
  { id: "13068491", title: "كشف المُخبَّا عن فنون أوربا", category: "history" },
  { id: "52020249", title: "سوانح الأميرة", category: "history" },
  { id: "63639520", title: "الرحلة اليابانية", category: "history" },
  { id: "35947928", title: "السفر إلى المؤتمر", category: "history" },
  { id: "59640846", title: "الدنيا في باريس", category: "history" },
  { id: "25817168", title: "رسائل أنقرة المقدسة", category: "history" },
  { id: "83804281", title: "في قلب نجد والحجاز", category: "history" },
  { id: "36319075", title: "رحلة الأندلس", category: "history" },
  { id: "72603515", title: "رحلة إلى الحجاز", category: "history" },
  { id: "48140315", title: "حُب الحياة", category: "novels", description: "رجل جائع ومصاب يزحف وحيداً عبر صحراء الجليد في كندا، وذئب مريض يتبعه منتظراً سقوطه." },
  { id: "90909497", title: "أخبار الحمقى والمغفلين", category: "literature", description: "نوادر ابن الجوزي المضحكة عن الحمقى والمغفلين عبر التاريخ." },
  { id: "93861582", title: "الإمتاع والمؤانسة", category: "literature", description: "ليالٍ من الحوار بين أبي حيان التوحيدي والوزير، في الأدب والفلسفة والطرائف." },
  { id: "24684962", title: "الفضيلة", category: "novels", description: "تعريب المنفلوطي لقصة «بول وفرجيني»: حب طاهر بين صبي وفتاة نشآ معاً في جزيرة بعيدة." },
  { id: "91827302", title: "الأرواح المتمردة", category: "novels", description: "قصص جبران القصيرة عن أرواح تمردت على ظلم المجتمع والكنيسة والإقطاع." },
  { id: "29373683", title: "العبرات", category: "novels", description: "قصص المنفلوطي المؤثرة، مؤلَّفة ومعرَّبة، عن الحب والفقر والظلم والتضحية." },
  { id: "63950852", title: "حديث عيسى بن هشام", category: "novels", description: "رحلة خيالية لباشا يُبعث من قبره في القاهرة، فيرى مع الراوي عجائب المجتمع الجديد بعين ساخرة." },
  { id: "85258647", title: "العواصف", category: "literature", description: "قصص ومقالات جبران الثائرة على التقاليد والظلم." },
  { id: "68407095", title: "دمعة وابتسامة", category: "literature", description: "مقالات وقصائد نثرية لجبران عن الحب والجمال والحياة والموت." },
  { id: "26919142", title: "شينجو", category: "novels" },
  { id: "94274146", title: "قصة تطوُّر مُعلِّم", category: "novels" },
  { id: "38168270", title: "تميمة حظ رورينج كامب", category: "novels" },
  { id: "47415942", title: "منبوذو بوكر فلات", category: "novels" },
  { id: "94830802", title: "نيجور الجبان", category: "novels" },
  { id: "84975206", title: "آثار الشمس الكاذبة", category: "novels" },
  { id: "59425757", title: "الكافر", category: "novels" },
  { id: "59209171", title: "نام-بوك الكذاب", category: "novels" },
  { id: "29297191", title: "حكاية رعب", category: "novels" },
  { id: "41907140", title: "الصعلوك والحورية", category: "novels" },
  { id: "46979506", title: "أمانة", category: "novels" },
  { id: "15020962", title: "المنديل الأصفر", category: "novels" },
  { id: "75707574", title: "نحو الغرب", category: "novels" },
  { id: "28164950", title: "العربة السماوية", category: "novels" },
  { id: "30792426", title: "أسلوب الرجل الأبيض", category: "novels" },
  { id: "30526809", title: "إقامة يوم واحد", category: "novels" },
  { id: "75862428", title: "الجانب الآخر من السياج", category: "novels" },
  { id: "26818153", title: "اللامتوقع", category: "novels" },
  { id: "85813068", title: "صور بلونَي اللافندر: الأزرق والأخضر", category: "novels" },
  { id: "30639474", title: "ذلك الكلب سبوت", category: "novels" },
  { id: "83971731", title: "حكاية كيش", category: "novels" },
  { id: "61586203", title: "مجرد قطعة لحم", category: "novels" },
  { id: "28524640", title: "أخدود الذهب الخالص", category: "novels" },
  { id: "64931350", title: "رسائل من تاجر عصامي إلى ابنه", category: "novels" },
  { id: "58375937", title: "براون وولف", category: "novels" },
  { id: "53594257", title: "أنف للملك", category: "novels" },
  { id: "69263975", title: "مختارات من القصص القصيرة", category: "novels" },
  { id: "81964971", title: "إغواء تافرنيك", category: "novels" },
  { id: "37573972", title: "واحد منا", category: "novels" },
  { id: "30257392", title: "مكايد الحب في قصور الملوك", category: "novels" },
  { id: "96241536", title: "نوادر حافظ نجيب", category: "literature" },
  { id: "36050924", title: "البؤساء في عصور الإسلام", category: "novels" },
  { id: "82731791", title: "مرور في أرض الهناء ونبأ من عالم البقاء", category: "novels" },
  { id: "25194053", title: "غرائب المكتوبجي", category: "literature" },
  { id: "48196908", title: "مشهد الأحوال", category: "novels" },
  { id: "85927947", title: "ليالي الروح الحائر", category: "novels" },
  { id: "52602647", title: "السابق", category: "novels" },
  { id: "83964838", title: "الاعتراف: وهو قصة نفس", category: "novels" },
  { id: "84242969", title: "قصص عن أناتول فرانس", category: "novels" },
  { id: "82863627", title: "نوادر الخلفاء", category: "literature" },
  { id: "35072052", title: "السراب", category: "novels" },
  { id: "13028368", title: "لؤلؤة الحب", category: "novels" },
  { id: "90504631", title: "مملكة جهنم والخمر", category: "novels" },
  { id: "29694805", title: "خواطر حمار: مذكرات فلسفية وأخلاقية على لسان حمار", category: "children" },
  { id: "14959242", title: "ما تراه العيون: قطع قصصية مصرية", category: "novels" },
  { id: "26375942", title: "طيف ملكي", category: "novels" },
  { id: "95392585", title: "أسباب الطرب في نوادر العرب", category: "literature" },
  { id: "28068295", title: "مذكرات عربجي", category: "novels" },
  { id: "86860817", title: "قصص روسية", category: "novels" },
  { id: "15792571", title: "نوادر الأدباء", category: "literature" },
  { id: "79405794", title: "النوادر المُطربة", category: "literature" },
  { id: "46050302", title: "مناجاة أرواح", category: "novels" },
  { id: "52849381", title: "نوادر العُشَّاق", category: "literature" },
  { id: "38246146", title: "نوادر الكرام", category: "literature" },
  { id: "95382805", title: "الوعظ القصصي", category: "novels" },
  { id: "17136091", title: "ابتسامات ودموع", category: "novels" },
  { id: "39714175", title: "رجوع الموجة", category: "novels" },
  { id: "90306293", title: "الحب في التاريخ", category: "novels" },
  { id: "39150590", title: "ليالي سطيح", category: "novels" },
  { id: "85938393", title: "صندوق الدنيا", category: "novels" },
  { id: "25291464", title: "يوليوس قيصر", category: "literature", film: "Julius Caesar (1953)", description: "مسرحية شكسبير عن مؤامرة اغتيال يوليوس قيصر وما تلاها من حرب." },
  { id: "71619149", title: "سيرانو دي برجراك", category: "literature", film: "Cyrano de Bergerac (1950، 1990)", description: "سيرانو الشاعر الشجاع ذو الأنف الطويل يكتب رسائل الحب لحبيبته باسم رجل آخر." },
  { id: "62708494", title: "عُطَيل", category: "literature", film: "Othello (1952، 1995)", description: "مأساة شكسبير عن القائد عطيل الذي يدمّره الشك والغيرة بمكيدة من ياجو." },
  { id: "39797960", title: "تاجر البندقية", category: "literature", film: "The Merchant of Venice (2004)", description: "تاجر يقترض من المرابي شايلوك ويرهن رطلاً من لحمه، في واحدة من أشهر مسرحيات شكسبير." },
  { id: "63131904", title: "أبو الحسن المغفل: رواية هارون الرشيد · رواية مضحكة مُلحنة ذات ثلاث فصول", category: "literature" },
  { id: "48592426", title: "سرقة", category: "literature" },
  { id: "58630741", title: "حيل النساء", category: "literature" },
  { id: "35251309", title: "عنتر بن شداد: تاريخية أدبية غرامية حربية تلحينية تشخيصية ذات أربعة فصول", category: "literature" },
  { id: "42093681", title: "الغلامان الأسيران", category: "literature" },
  { id: "50840694", title: "هارون الرشيد مع أنس الجليس", category: "literature" },
  { id: "90402574", title: "الثقلاء", category: "literature" },
  { id: "70973937", title: "الحكيم الطيار", category: "literature" },
  { id: "29684682", title: "غرائب الصدف", category: "literature" },
  { id: "74806249", title: "هارون الرشيد مع الأمير غانم بن أيوب وقوت القلوب: رواية تاريخية غرامية أدبية تلحينية تشخيصية", category: "literature" },
  { id: "26859382", title: "الظلوم", category: "literature" },
  { id: "19268374", title: "فتح الأندلس", category: "literature" },
  { id: "25969138", title: "الشبح الأبيض", category: "literature" },
  { id: "62705842", title: "لباب الغرام", category: "literature" },
  { id: "53624727", title: "الشيخ متلوف", category: "literature" },
  { id: "64803140", title: "مدرسة الأزواج", category: "literature" },
  { id: "18240308", title: "الخدامين والمخدمين", category: "literature" },
  { id: "62031951", title: "مي", category: "literature" },
  { id: "51803716", title: "الأمير محمود نجل شاه العجم", category: "literature" },
  { id: "53581373", title: "ناكر الجميل", category: "literature" },
  { id: "83591793", title: "عبد الستار أفندي: كوميديا مصرية أخلاقية ذات أربعة فصول", category: "literature" },
  { id: "41390640", title: "فرَّان البندقية: مأساة ذات خمسة فصول", category: "literature" },
  { id: "40471518", title: "الذكرى", category: "literature" },
  { id: "52707961", title: "أشباح القرن الثامن عشر", category: "literature" },
  { id: "42047964", title: "المأساة الكبرى: رواية تشخيصية في الحرب الحاضرة", category: "literature" },
  { id: "36308593", title: "موليير مصر وما يقاسيه", category: "literature" },
  { id: "60591692", title: "الأميرة الإسكندرانية", category: "literature" },
  { id: "93028137", title: "مجنون ليلى: مأساة غرامية أدبية تاريخية ذات خمس فصول", category: "literature" },
  { id: "51692820", title: "بورصة مصر", category: "literature" },
  { id: "75969724", title: "الأخرس المتكلم", category: "literature" },
  { id: "27046930", title: "الطبيب على الرغم منه", category: "literature" },
  { id: "36028068", title: "توادوسيوس قيصر: مأساة تاريخية تمثيلية ذات ثلاثة فصول", category: "literature" },
  { id: "94742841", title: "أندروماك: مسرحية تشخيصية ذات خمسة فصول", category: "literature" },
  { id: "97425906", title: "عزة بنت الخليفة: رواية تمثيلية ذات فصل واحد", category: "literature" },
  { id: "14948082", title: "العصفور في القفص: كوميدي مصرية ذات أربعة فصول", category: "literature" },
  { id: "31492590", title: "الوزير ابن زَيْدون مع وَلَّادة بنت المستكفي", category: "literature" },
  { id: "94064849", title: "الرجاء بعد اليأس", category: "literature" },
  { id: "13680727", title: "البدوية", category: "literature" },
  { id: "14942790", title: "السموأل: رواية تمثيلية ذات أربعة فصول", category: "literature" },
  { id: "90294913", title: "أردشير وحياة النفوس: قصة غرامية تلحينية", category: "literature" },
  { id: "19631595", title: "كريستوف كولومب", category: "literature" },
  { id: "26085284", title: "زينوبيا ملكة تدمر: أوبرا تاريخية كبرى ذات أربعة فصول", category: "literature" },
  { id: "40350828", title: "ثارات العرب: أدبية تاريخية غرامية تشخيصية", category: "literature" },
  { id: "42736927", title: "إحسان: مأساة مصرية تلحينية", category: "literature" },
  { id: "15917424", title: "ابن الشعب", category: "literature" },
  { id: "81308482", title: "الشاردة", category: "literature" },
  { id: "38057286", title: "مصرع كليوباترا", category: "literature" },
  { id: "36024294", title: "حلم أغسطس", category: "literature" },
  { id: "86815080", title: "الهواري: رواية تلحينية عربية ذات فصل واحد", category: "literature" },
  { id: "86085746", title: "البخيلة", category: "literature" },
  { id: "13950286", title: "صلاح الدين الأيوبي وعصره", category: "history", film: "الناصر صلاح الدين (1963)، Kingdom of Heaven (2005)", description: "سيرة صلاح الدين الأيوبي وحروبه مع الصليبيين وتحرير القدس." },
  { id: "48179527", title: "كولومب والعالم الجديد: تاريخ اكتشاف أميركا", category: "history", film: "1492: Conquest of Paradise (1992)", description: "قصة كريستوفر كولومبس ورحلاته التي انتهت باكتشاف أمريكا." },
  { id: "35825168", title: "نابوليون بونابارت في مصر", category: "history", film: "Napoleon (2023)", description: "حملة نابليون على مصر وما جرى فيها من معارك وأحداث." },
  { id: "74257591", title: "فتح العرب لمصر", category: "history" },
  { id: "18482097", title: "مصارع العشاق", category: "history" },
  { id: "80313908", title: "أبطال مصر", category: "history" },
  { id: "91582486", title: "تاريخ وليم الظافر", category: "history" },
  { id: "17160604", title: "عصر المأمون", category: "history" },
  { id: "74640940", title: "مصارع الخلفاء", category: "history" },
  { id: "53158280", title: "السيف والنار في السودان", category: "history" },
  { id: "84857157", title: "تاريخ آل رومانوف", category: "history" },
  { id: "46069628", title: "خلاصة تاريخ العراق: منذ نشوئه إلى يومنا هذا", category: "history" },
  { id: "49493751", title: "مختصر تاريخ البصرة", category: "history" },
  { id: "60208373", title: "الدولة الأموية في الشام", category: "history" },
  { id: "83191846", title: "عصر العرب الذهبي", category: "history" },
  { id: "59140940", title: "على ضفاف النيل: في عصر الفراعنة", category: "history" },
  { id: "36305860", title: "النسر الأعظم", category: "history" },
  { id: "79183807", title: "نوادر الحرب العظمى", category: "history" },
  { id: "51620274", title: "غابر الأندلس وحاضرها", category: "history" },
  { id: "86061691", title: "خلاصة تاريخ العرب", category: "history" },
  { id: "92024806", title: "فجر الإسلام", category: "history" },
  { id: "92963020", title: "ظهر الإسلام", category: "history" },
  { id: "26382506", title: "تاريخ التمدن الإسلامي (الجزء الأول)", category: "history" },
  { id: "18683707", title: "تاريخ التمدن الإسلامي (الجزء الثاني)", category: "history" },
  { id: "30690257", title: "تاريخ التمدن الإسلامي (الجزء الثالث)", category: "history" },
  { id: "17928316", title: "تاريخ التمدن الإسلامي (الجزء الرابع)", category: "history" },
  { id: "72973614", title: "تاريخ التمدن الإسلامي (الجزء الخامس)", category: "history" },
  { id: "70379519", title: "عجايب الآثار في التراجم والأخبار (الجزء الأول)", category: "history" },
  { id: "38614175", title: "عجايب الآثار في التراجم والأخبار (الجزء الثاني)", category: "history" },
  { id: "58463626", title: "عجايب الآثار في التراجم والأخبار (الجزء الثالث)", category: "history" },
  { id: "53519152", title: "عجايب الآثار في التراجم والأخبار (الجزء الرابع)", category: "history" },
  { id: "51685040", title: "عجايب الآثار في التراجم والأخبار (الجزء الخامس)", category: "history" },
  { id: "24697404", title: "تاريخ مصر في عهد الخديو إسماعيل باشا", category: "history" },
  { id: "69702740", title: "نهضة مصر", category: "history" },
];

const BY_ID = new Map(HINDAWI_PICKS.map((p) => [p.id, p]));

export function hindawiPick(id: string): HindawiPick | undefined {
  return BY_ID.get(id);
}
